Repository se4ai2122-cs-uniba/CT-COVID, pull requests merged in 2021-12, with the labels that each got.

#23 Simplified Docker image and added useful scripts
  .dockerignore
  Dockerfile
  scripts/build-docker-image.sh
  scripts/run-docker-cpu.sh
  scripts/run-docker-cuda.sh
Labels: enhancement

#26 Added DVC evaluation stage
  dvc.lock
  dvc.yaml
  metrics/.gitignore
  metrics/ct_net-clf-metrics.json
  params.yaml
  src/evaluate.py
Labels: enhancement

#29 Added locust script
  scripts/run-locust.sh
  test/locust.py
Labels: enhancement

#31 Added DVC evaluation sage params field in dvc.yaml
  dvc.lock
  dvc.yaml
Labels: bug

#34 Introduce Great Expectations v3 for data testing
  scripts/run-great-expectations.sh
  tests/great_expectations/.gitignore
  tests/great_expectations/checkpoints/ct-test.yml
  tests/great_expectations/checkpoints/ct-train.yml
  tests/great_expectations/checkpoints/ct-valid.yml
  tests/great_expectations/expectations/.ge_store_backend_id
  tests/great_expectations/expectations/test/csv/warning.json
  tests/great_expectations/expectations/train/csv/warning.json
  tests/great_expectations/expectations/valid/csv/warning.json
  tests/great_expectations/great_expectations.yml
  tests/great_expectations/plugins/custom_data_docs/styles/data_docs_custom_styles.css
Labels: enhancement

#39 Prometheus
  prometheus.yml
  requirements.txt
  requirements_dev.txt
  scripts/run-prometheus.sh
  src/api.py
  src/monitoring.py
Labels: enhancement

#46 Linter GitHub Action
  .github/workflows/linter.yml
  README.md
  pylintrc
Labels: documentation

#56 Review and refactor of bash scripts
  scripts/build-docker-backend.sh
  scripts/build-docker-image.sh
  scripts/run-docker-cpu.sh
  scripts/run-docker-cuda.sh
  scripts/run-grafana-linux.sh
  scripts/run-prometheus-linux.sh
  scripts/run-prometheus.sh
  scripts/run-pytest-cpu.sh
  scripts/run-pytest-cuda.sh
  scripts/run-pytest.sh
Labels: documentation

#59 Added line for fixing issue #57
  src/monitoring.py
Labels: bug
