Repository se4ai2122-cs-uniba/CT-COVID, pull requests merged in 2021-11, with the labels that each got.

#2 Issue dvc
  .dvc/.gitignore
  .dvc/config
  .dvc/plots/confusion.json
  .dvc/plots/confusion_normalized.json
  .dvc/plots/linear.json
  .dvc/plots/scatter.json
  .dvc/plots/simple.json
  .dvc/plots/smooth.json
  .dvcignore
  covidx/ct/preprocessing.py
  covidx/ct/seq_preprocessing.py
  data/.gitignore
  data/raw.dvc
  dvc.lock
  dvc.yaml
  params.yaml
  requirements.txt
Labels: good first issue

#11 Fix checkpoint and early stopping during training
  src/covidx/utils/torch.py
  src/covidx/utils/train.py
  src/experiments.py
Labels: bug

#16 Docker integration
  .dockerignore
  Dockerfile
  src/api.py
Labels: enhancement

#18 Added API documentation and some fixes regarding PyTorch and data preprocessing
  dvc.lock
  src/api.py
  src/experiments.py
Labels: documentation, enhancement
